"use client";

import React, { useState, useRef, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';

type UI_STATE = 'LOADING_REPO' | 'REPO_DASHBOARD';

interface GitHubIssue {
  title: string;
  number: number;
  url: string;
  author: string;
  created_at: string;
  body_snippet: string;
}

interface RepoFile {
  path: string;
  size: number;
  type: string;
}

export default function RepoDashboard() {
  const params = useParams();
  const router = useRouter();
  const owner = params.owner as string;
  const repo = params.repo as string;
  const repoUrl = `https://github.com/${owner}/${repo}`;

  const [uiState, setUiState] = useState<UI_STATE>('LOADING_REPO');
  const [repoInfo, setRepoInfo] = useState<{ tree: RepoFile[], issues: GitHubIssue[] } | null>(null);
  const [selectedFilePath, setSelectedFilePath] = useState<string | null>(null);
  const [selectedFileContent, setSelectedFileContent] = useState<string>("");
  const [isLoadingFile, setIsLoadingFile] = useState(false);
  const [error, setError] = useState("");

  const [issueUrl, setIssueUrl] = useState("");
  const [runConfidence] = useState(true);
  const [running, setRunning] = useState(false);
  const [statusName, setStatusName] = useState("");
  const [statusMessage, setStatusMessage] = useState("");
  const [streamChunks, setStreamChunks] = useState<string[]>([]);
  const [result, setResult] = useState<any>(null);
  const [analyzingFiles, setAnalyzingFiles] = useState<string[]>([]);
  const [terminalExpanded, setTerminalExpanded] = useState(true);
  const [completedSteps, setCompletedSteps] = useState<{step: string, message: string, status: string}[]>([]);
  const [fixedFileView, setFixedFileView] = useState<{path: string, content: string} | null>(null);
  const [sessionId, setSessionId] = useState("");
  const [feedback, setFeedback] = useState("");
  const [newFiles, setNewFiles] = useState<string[]>([]);  // files generated by agent, not in original tree
  const resultRef = useRef<any>(null);  // avoid stale closure in eof handler

  const logsEndRef = useRef<HTMLDivElement>(null);

  // Auto-load repo on mount
  useEffect(() => {
    const loadRepo = async () => {
      try {
        const res = await fetch(`/api/repo_info?repo_url=${encodeURIComponent(repoUrl)}`);
        if (!res.ok) {
          const data = await res.json();
          throw new Error(data.detail || "Failed to fetch repository info");
        }
        const data = await res.json();
        setRepoInfo(data);
        setUiState('REPO_DASHBOARD');
        if (data.tree && data.tree.length > 0) {
          handleFileClick(data.tree[0].path, repoUrl);
        }
      } catch (err: any) {
        setError(err.message);
      }
    };
    loadRepo();
  }, [owner, repo]);

  useEffect(() => {
    if (logsEndRef.current) {
      logsEndRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [streamChunks, statusMessage, running]);

  useEffect(() => {
    if (statusMessage) {
      const pathRegex = /([a-zA-Z0-9._\-/]+\.(py|js|tsx|ts|html|css|json|md))/g;
      const matches = statusMessage.match(pathRegex);
      if (matches) {
        setAnalyzingFiles(prev => [...new Set([...prev, ...matches])]);
        const validPath = matches.find(p => repoInfo?.tree.some(f => f.path === p));
        if (validPath && validPath !== selectedFilePath) {
          handleFileClick(validPath, repoUrl);
        }
      }
    }
  }, [statusMessage]);

  const handleFileClick = async (path: string, url?: string) => {
    const repoUrlToUse = url || repoUrl;
    setSelectedFilePath(path);
    setIsLoadingFile(true);
    try {
      const res = await fetch(`/api/file_content?repo_url=${encodeURIComponent(repoUrlToUse)}&file_path=${encodeURIComponent(path)}`);
      if (!res.ok) throw new Error("Failed to fetch file content");
      const data = await res.json();
      setSelectedFileContent(data.content);
    } catch {
      setSelectedFileContent("// Error loading file content...");
    } finally {
      setIsLoadingFile(false);
    }
  };

  const handleAnalyze = (selectedIssueUrl?: string) => {
    const finalIssueUrl = selectedIssueUrl || issueUrl;
    if (!finalIssueUrl) { setError("Please provide an Issue URL"); return; }

    setRunning(true);
    setError("");
    setResult(null);
    setStreamChunks([]);
    setAnalyzingFiles([]);
    setCompletedSteps([]);
    setFixedFileView(null);
    setTerminalExpanded(true);
    setStatusName("Starting");
    setStatusMessage("Connecting to FixFlow API...");

    const params = new URLSearchParams({ issue_url: finalIssueUrl, repo_url: repoUrl, run_confidence: runConfidence.toString() });
    const eventSource = new EventSource(`/api/analyze?${params.toString()}`);
    setupEventSource(eventSource);
  };

  const handleRefine = () => {
    if (!feedback || !sessionId) return;
    setRunning(true);
    setError("");
    setStreamChunks([]);
    setAnalyzingFiles([]);
    setCompletedSteps([]);
    setFixedFileView(null);
    setTerminalExpanded(true);
    setStatusName("Refining");
    setStatusMessage("Sending feedback to FixFlow...");
    const params = new URLSearchParams({ session_id: sessionId, feedback });
    setFeedback("");
    const eventSource = new EventSource(`/api/refine?${params.toString()}`);
    setupEventSource(eventSource);
  };

  const setupEventSource = (eventSource: EventSource) => {
    eventSource.addEventListener("status", (e: Event) => {
      const data = JSON.parse((e as MessageEvent).data);
      const { step, status, message } = data;
      setStatusName(step);
      setStatusMessage(message);
      if (status === "complete" || status === "error") {
        setCompletedSteps(prev => [...prev, { step, status, message }]);
      }
    });
    eventSource.addEventListener("stream", (e: Event) => {
      const data = JSON.parse((e as MessageEvent).data);
      setStreamChunks(prev => [...prev, data.chunk]);
    });
    eventSource.addEventListener("done", (e: Event) => {
      const data = JSON.parse((e as MessageEvent).data);
      const r = data.result;
      setResult(r);
      resultRef.current = r;
      if (data.session_id) setSessionId(data.session_id);
      if (r?.fixed_files) {
        const paths = Object.keys(r.fixed_files);
        // Show first fixed file in editor
        if (paths.length > 0) {
          setFixedFileView({ path: paths[0], content: r.fixed_files[paths[0]] });
          setSelectedFilePath(paths[0]);
        }
        // Inject any new files into the explorer tree
        setRepoInfo(prev => {
          if (!prev) return prev;
          const existingPaths = new Set(prev.tree.map(f => f.path));
          const addedPaths = paths.filter(p => !existingPaths.has(p));
          setNewFiles(addedPaths);
          if (addedPaths.length === 0) return prev;
          const newEntries = addedPaths.map(p => ({ path: p, size: 0, type: 'blob' }));
          return { ...prev, tree: [...prev.tree, ...newEntries] };
        });
      }
    });
    eventSource.addEventListener("error", (e: Event) => {
      const data = JSON.parse((e as MessageEvent).data);
      setError(data.error || "Unknown stream error");
      setRunning(false);
      eventSource.close();
    });
    eventSource.addEventListener("eof", () => {
      setRunning(false);
      setStatusName("Done");
      setStatusMessage("Fix generated — review the highlighted file in the editor.");
      setCompletedSteps(prev => [...prev, { step: "done", status: "complete", message: "Fix generated — review highlighted file!" }]);
      eventSource.close();
    });
    eventSource.addEventListener("heartbeat", () => {});
    eventSource.onerror = (e) => console.error("SSE Error:", e);
  };

  const handleOpenPR = async () => {
    if (!result) return;
    try {
      const res = await fetch("/api/pr", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          repo_url: repoUrl,
          title: result.issue_title,
          body: result.fix_explanation + "\n\n---\n*Generated autonomously by FixFlow*",
          fixed_files: result.fixed_files
        })
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.detail || "Failed to create PR");
      window.open(data.url, "_blank");
    } catch (err: any) { alert("Error: " + err.message); }
  };

  // ── Loading Screen ────────────────────────────────────────────────────────
  if (uiState === 'LOADING_REPO') {
    return (
      <div style={{ height: '100vh', display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
        <div style={{ 
          display: 'flex', 
          alignItems: 'center', 
          gap: 16, 
          padding: '12px 32px', 
          borderBottom: '1px solid var(--border-color)', 
          flexShrink: 0,
          background: 'rgba(0, 0, 0, 0.5)',
          backdropFilter: 'blur(10px)'
        }}>
          <span style={{ fontSize: '1.5rem', cursor: 'pointer' }} onClick={() => router.push('/')}>🔧</span>
          <span style={{ 
            fontWeight: 800, 
            fontSize: '1.3rem', 
            color: 'var(--text-main)'
          }}>
            FixFlow
          </span>
          <span style={{ color: 'var(--border-color)', fontSize: '1.2rem' }}>/</span>
          <span style={{ color: 'var(--text-muted)', fontSize: '0.95rem', fontFamily: 'monospace' }}>
            {owner} / {repo}
          </span>
        </div>
        <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', flexDirection: 'column', gap: 24 }}>
          <div className="loading-spinner" style={{ width: 48, height: 48 }} />
          <div style={{ textAlign: 'center' }}>
            <p style={{ color: 'var(--text-main)', fontSize: '1.2rem', fontWeight: 600, marginBottom: 8 }}>
              Analyzing Repository
            </p>
            <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>
              Cloning <span className="gradient-text" style={{ fontWeight: 600 }}>{owner}/{repo}</span>
            </p>
          </div>
          <div style={{ display: 'flex', gap: 12, marginTop: 16 }}>
            <div className="timeline-item" style={{ border: 'none', padding: 0 }}>
              <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Fetching files...</span>
            </div>
          </div>
          {error && (
            <div style={{ 
              color: 'var(--error)', 
              fontSize: '0.85rem', 
              background: 'rgba(239, 68, 68, 0.1)', 
              padding: 16, 
              borderRadius: 8,
              border: '1px solid rgba(239, 68, 68, 0.3)',
              maxWidth: 400
            }}>
              ❌ {error}
            </div>
          )}
        </div>
      </div>
    );
  }

  // ── IDE Dashboard ─────────────────────────────────────────────────────────
  if (!repoInfo) return null;

  return (
    <div style={{ height: '100vh', display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
      {/* Vercel-style Top Bar */}
      <div style={{ 
        display: 'flex', 
        alignItems: 'center', 
        gap: 16, 
        padding: '12px 32px', 
        borderBottom: '1px solid var(--border-color)', 
        flexShrink: 0,
        background: 'rgba(0, 0, 0, 0.5)',
        backdropFilter: 'blur(10px)'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, cursor: 'pointer' }} onClick={() => router.push('/')}>
          <span style={{ fontSize: '1.5rem' }}>🔧</span>
          <span style={{ 
            fontWeight: 800, 
            fontSize: '1.3rem', 
            color: 'var(--text-main)'
          }}>
            FixFlow
          </span>
        </div>
        <span style={{ color: 'var(--border-color)', fontSize: '1.2rem' }}>/</span>
        <a href={repoUrl} target="_blank" rel="noreferrer" style={{ 
          color: 'var(--text-muted)', 
          fontSize: '0.95rem', 
          fontFamily: 'monospace', 
          textDecoration: 'none',
          display: 'flex',
          alignItems: 'center',
          gap: 6
        }}>
          <span style={{ opacity: 0.7 }}>{owner}</span>
          <span style={{ color: 'var(--border-color)' }}>/</span>
          <strong style={{ color: 'var(--text-main)' }}>{repo}</strong>
        </a>
        <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 20 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <span className="stat-badge" style={{ fontSize: '0.7rem' }}>
              📁 {repoInfo.tree.length} files
            </span>
            <span className="stat-badge" style={{ fontSize: '0.7rem' }}>
              🐛 {repoInfo.issues.length} issues
            </span>
          </div>
          <span className="status-online" style={{ fontSize: '0.75rem' }}>Live</span>
        </div>
      </div>

      {/* Main IDE */}
      <div style={{ flex: 1, padding: '16px', display: 'flex', overflow: 'hidden' }}>
        <div style={{ display: 'grid', gridTemplateColumns: '240px 1fr 300px', gap: 16, flex: 1, minHeight: 0 }}>

          {/* Left: Explorer */}
          <div className="glass-panel" style={{ padding: 16, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }}>
              <h3 style={{ fontSize: '0.75rem', color: 'var(--text-muted)', letterSpacing: '0.1em', fontWeight: 600 }}>
                📁 EXPLORER
              </h3>
              <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>
                {repoInfo.tree.length}
              </span>
            </div>
            <div style={{ 
              flex: 1, 
              overflowY: 'auto', 
              fontSize: '0.78rem', 
              color: 'var(--text-muted)', 
              fontFamily: 'monospace',
              paddingRight: 4
            }}>
              {repoInfo.tree.map((file, i) => {
                const isAnalyzing = analyzingFiles.includes(file.path);
                const isNew = newFiles.includes(file.path);
                const isFixed = result?.fixed_files && file.path in result.fixed_files && !isNew;
                return (
                  <div
                    key={i}
                    onClick={() => {
                      if (isNew || isFixed) {
                        setSelectedFilePath(file.path);
                        setFixedFileView({ path: file.path, content: result.fixed_files[file.path] });
                      } else {
                        handleFileClick(file.path);
                        setFixedFileView(null);
                      }
                    }}
                    className={isAnalyzing ? 'analyzing-glow' : ''}
                    style={{
                      padding: '6px 10px',
                      cursor: 'pointer',
                      borderRadius: '6px',
                      marginBottom: '2px',
                      backgroundColor: selectedFilePath === file.path ? 'rgba(99, 102, 241, 0.12)' : 'transparent',
                      color: isNew ? '#10b981' : isFixed ? '#f59e0b' : selectedFilePath === file.path ? 'var(--primary)' : 'inherit',
                      whiteSpace: 'nowrap',
                      overflow: 'hidden',
                      textOverflow: 'ellipsis',
                      transition: 'all 0.2s ease',
                      border: selectedFilePath === file.path ? '1px solid rgba(99, 102, 241, 0.25)' : '1px solid transparent'
                    }}
                  >
                    <span style={{ marginRight: 8, fontSize: '0.9rem' }}>
                      {isAnalyzing ? '🧠' : isNew ? '✨' : isFixed ? '✏️' : '📄'}
                    </span>
                    {file.path}
                    {isNew && <span style={{ marginLeft: 8, fontSize: '0.65rem', color: '#10b981', opacity: 0.9, fontWeight: 600 }}>NEW</span>}
                    {isFixed && <span style={{ marginLeft: 8, fontSize: '0.65rem', color: '#f59e0b', opacity: 0.9, fontWeight: 600 }}>MOD</span>}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Center: Editor + Terminal Drawer */}
          <div style={{ display: 'flex', flexDirection: 'column', minHeight: 0, minWidth: 0 }}>
            <div className="terminal-window" style={{ flex: 1, display: 'flex', flexDirection: 'column', borderBottomLeftRadius: 0, borderBottomRightRadius: 0, minHeight: 0 }}>
              <div className="terminal-header">
                <div className="terminal-dot dot-red"></div>
                <div className="terminal-dot dot-yellow"></div>
                <div className="terminal-dot dot-green"></div>
                <div style={{ marginLeft: '12px', fontSize: '0.75rem', color: 'var(--text-muted)', fontFamily: 'monospace' }}>
                  {running && (statusName === '4_fix' || statusName === '4_refine') ? '🔧 Generating Fix...' : selectedFilePath || 'Editor'}
                </div>
              </div>
              <div style={{ flex: 1, overflow: 'auto', backgroundColor: '#0d0d12' }}>
                {fixedFileView && !running ? (
                  <pre style={{ margin: 0, padding: '20px', fontSize: '0.83rem', fontFamily: 'monospace', color: '#10b981', lineHeight: '1.6' }}>
                    {fixedFileView.content}
                  </pre>
                ) : running && (statusName === '4_fix' || statusName === '4_refine') && streamChunks.length > 0 ? (
                  <pre style={{ margin: 0, padding: '20px', fontSize: '0.83rem', fontFamily: 'monospace', color: '#10b981', lineHeight: '1.6' }}>
                    {streamChunks.join('')}
                    <span style={{ borderRight: '2px solid var(--primary)' }}> </span>
                    <div ref={logsEndRef} />
                  </pre>
                ) : (
                  <pre style={{ margin: 0, padding: '20px', fontSize: '0.83rem', fontFamily: 'monospace', color: '#d1d5db', lineHeight: '1.6' }}>
                    {selectedFileContent || '// Select a file to browse source code'}
                  </pre>
                )}
              </div>
            </div>

            {/* Terminal Drawer */}
            <div className="terminal-drawer" style={{ height: terminalExpanded ? '200px' : '40px', borderRadius: '0 0 12px 12px' }}>
              <div className="terminal-drawer-header" onClick={() => setTerminalExpanded(!terminalExpanded)}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                  {running && <span className="loading-spinner" style={{ width: 12, height: 12 }} />}
                  <span style={{ color: running ? 'var(--primary)' : 'var(--text-muted)' }}>
                    {statusName ? `AGENT — [${statusName.toUpperCase()}]` : 'FIXFLOW AGENT CONSOLE'}
                  </span>
                </div>
                <span>{terminalExpanded ? '▼' : '▲ Show Progress'}</span>
              </div>
              <div className="terminal-drawer-body" style={{ padding: '10px 16px' }}>
                {completedSteps.map((s, i) => (
                  <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6, fontSize: '0.78rem' }}>
                    <span style={{ color: s.status === 'error' ? 'var(--error)' : 'var(--success)', flexShrink: 0 }}>
                      {s.status === 'error' ? '✗' : '✓'}
                    </span>
                    <span style={{ color: 'var(--text-muted)' }}>{s.message}</span>
                  </div>
                ))}
                {running && statusMessage && (
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10, fontSize: '0.78rem' }}>
                    <span className="loading-spinner" style={{ width: 10, height: 10, flexShrink: 0 }} />
                    <span style={{ color: 'var(--primary)' }}>{statusMessage}</span>
                  </div>
                )}
                <div ref={logsEndRef} />
              </div>
            </div>
          </div>

          {/* Right: Discovery or Result */}
          <div className="glass-panel" style={{ padding: 16, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
            {result && !running ? (
              <>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
                  <h3 style={{ fontSize: '0.85rem', color: 'var(--success)', fontWeight: 600 }}>✅ FIX READY</h3>
                  <div className="pulse-dot" style={{ width: 6, height: 6 }}></div>
                </div>
                <p style={{ fontSize: '0.72rem', color: 'var(--text-muted)', marginBottom: 16, lineHeight: 1.5 }}>
                  {result.bug_summary?.slice(0, 150)}...
                </p>
                <div style={{ marginBottom: 16 }}>
                  <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)', marginBottom: 8, letterSpacing: '0.1em', fontWeight: 600 }}>
                    CHANGED FILES
                  </div>
                  {Object.keys(result.fixed_files || {}).map((path) => (
                    <div
                      key={path}
                      onClick={() => setFixedFileView({ path, content: result.fixed_files[path] })}
                      style={{
                        padding: '8px 12px', 
                        borderRadius: 6, 
                        marginBottom: 6, 
                        cursor: 'pointer',
                        fontSize: '0.72rem', 
                        fontFamily: 'monospace',
                        backgroundColor: fixedFileView?.path === path ? 'rgba(16, 185, 129, 0.1)' : 'rgba(255,255,255,0.03)',
                        color: fixedFileView?.path === path ? '#10b981' : 'var(--text-muted)',
                        border: fixedFileView?.path === path ? '1px solid rgba(16, 185, 129, 0.3)' : '1px solid var(--border-color)',
                        whiteSpace: 'nowrap', 
                        overflow: 'hidden', 
                        textOverflow: 'ellipsis',
                        transition: 'all 0.2s ease'
                      }}
                    >
                      <span style={{ marginRight: 8 }}>📝</span>
                      {path}
                    </div>
                  ))}
                </div>
                <div style={{ flex: 1 }} />
                <button 
                  type="button" 
                  className="glow-btn" 
                  style={{ width: '100%', marginBottom: 10, padding: '12px', fontSize: '0.82rem' }} 
                  onClick={handleOpenPR}
                >
                  🚀 Open Pull Request
                </button>
                <div style={{ display: 'flex', gap: 8, marginBottom: 10 }}>
                  <input 
                    className="input-field" 
                    style={{ flex: 1, padding: '8px 10px', fontSize: '0.75rem' }}
                    placeholder="Refine the fix..." 
                    value={feedback}
                    onChange={(e) => setFeedback(e.target.value)}
                    onKeyDown={(e) => e.key === 'Enter' && handleRefine()} 
                  />
                  <button 
                    type="button" 
                    className="glow-btn" 
                    style={{ padding: '8px 14px', fontSize: '0.8rem' }} 
                    onClick={handleRefine} 
                    disabled={!feedback}
                  >
                    ↩
                  </button>
                </div>
                <button 
                  type="button" 
                  style={{ 
                    background: 'none', 
                    border: 'none', 
                    color: 'var(--text-muted)', 
                    cursor: 'pointer', 
                    fontSize: '0.72rem',
                    padding: '8px',
                    transition: 'color 0.2s'
                  }}
                  onClick={() => { setResult(null); setFixedFileView(null); setCompletedSteps([]); }}
                  onMouseEnter={(e) => e.currentTarget.style.color = 'var(--primary)'}
                  onMouseLeave={(e) => e.currentTarget.style.color = 'var(--text-muted)'}
                >
                  ← Pick another issue
                </button>
              </>
            ) : (
              <>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }}>
                  <h3 style={{ fontSize: '0.75rem', color: 'var(--text-muted)', letterSpacing: '0.1em', fontWeight: 600 }}>
                    🐛 ISSUES
                  </h3>
                  <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>
                    {repoInfo.issues.length}
                  </span>
                </div>
                <div style={{ flex: 1, overflowY: 'auto', paddingRight: 4 }}>
                  {repoInfo.issues.length === 0 ? (
                    <div style={{ 
                      textAlign: 'center', 
                      padding: '40px 20px',
                      color: 'var(--text-muted)',
                      fontSize: '0.8rem'
                    }}>
                      <div style={{ fontSize: '2rem', marginBottom: 12 }}>✨</div>
                      <p>No open issues found</p>
                    </div>
                  ) : repoInfo.issues.map((issue) => (
                    <div
                      key={issue.number}
                      className="repo-card"
                      style={{ 
                        cursor: running ? 'default' : 'pointer', 
                        padding: '12px', 
                        marginBottom: 10, 
                        opacity: running ? 0.5 : 1 
                      }}
                      onClick={() => !running && handleAnalyze(issue.url)}
                    >
                      <div style={{ 
                        display: 'flex', 
                        alignItems: 'center', 
                        gap: 8, 
                        marginBottom: 6 
                      }}>
                        <span style={{ 
                          fontSize: '0.7rem', 
                          color: 'var(--primary)', 
                          fontWeight: 600,
                          fontFamily: 'monospace'
                        }}>
                          #{issue.number}
                        </span>
                        <span style={{ 
                          fontSize: '0.78rem', 
                          fontWeight: 600,
                          color: 'var(--text-main)',
                          flex: 1,
                          overflow: 'hidden',
                          textOverflow: 'ellipsis',
                          whiteSpace: 'nowrap'
                        }}>
                          {issue.title}
                        </span>
                      </div>
                      <div style={{ fontSize: '0.68rem', color: 'var(--text-muted)' }}>
                        by @{issue.author}
                      </div>
                    </div>
                  ))}
                </div>
                {!running && (
                  <div style={{ borderTop: '1px solid var(--border-color)', paddingTop: 12, marginTop: 12 }}>
                    <input 
                      className="input-field" 
                      style={{ padding: '8px 12px', fontSize: '0.78rem', marginBottom: 8 }}
                      placeholder="Paste issue URL..." 
                      value={issueUrl} 
                      onChange={(e) => setIssueUrl(e.target.value)} 
                    />
                    <button 
                      type="button" 
                      className="glow-btn" 
                      style={{ width: '100%', padding: '10px', fontSize: '0.78rem' }}
                      onClick={() => handleAnalyze()} 
                      disabled={!issueUrl}
                    >
                      Analyze Issue
                    </button>
                  </div>
                )}
              </>
            )}
            {error && (
              <div style={{ 
                marginTop: 12, 
                fontSize: '0.75rem', 
                color: 'var(--error)',
                background: 'rgba(239, 68, 68, 0.1)',
                padding: 10,
                borderRadius: 6,
                border: '1px solid rgba(239, 68, 68, 0.3)'
              }}>
                ❌ {error}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
